### PR TITLE
Remove project

### PR DESCRIPTION
**Pull request by djmitche**

### CODE REVIEW

**Comment by jonasfj** [comment]
why?

**Comment by djmitche** [comment]
Because otherwise this shows up when you go looking for the scheduler code, and it is most certainly _not_ the scheduler code.

**Comment by djmitche** [comment]
..I've done this twice now, and @gregarndt has at least once.

**Comment by jonasfj** [comment]
How about we rename the repository "<repositoryName>-DEPRECATED" as a pattern for deprecated repositories..

Other ideas are welcome too?

Or we create an organization called "deprecated-repositories" and move deprecated repositories there :)

**Comment by jonasfj** [comment]
Note: We did the -DEPRECATED suffix once... and agreed it was nice... but we've only done it for one repository...

**Comment by djmitche** [comment]
That works for me.

**Pull request closed without merging**
